// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	Portfolios          string
	StockPrices         string
	TechnicalIndicators string
	WatchLists          string
}{
	Portfolios:          "portfolios",
	StockPrices:         "stock_prices",
	TechnicalIndicators: "technical_indicators",
	WatchLists:          "watch_lists",
}
