# Pre-commit hooks for Stock Automation Backend
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

  # Go specific hooks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        args: [-w]
      - id: go-imports
        args: [-w]
      - id: go-vet-mod
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: go-build-mod
      - id: go-cyclo
        args: [-over=15]
      - id: go-lint-golangci-lint
        args: [--timeout=5m]

  # Security hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # Dockerfile hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(yaml|yml|json|md)$
        exclude: ^(backend/go\.sum|\.golangci\.yml)$

  # Go security
  - repo: https://github.com/securecodewarrior/gosec
    rev: v2.18.2
    hooks:
      - id: gosec
        args: [-fmt=json, -out=gosec-report.json, -stdout, -verbose=text]

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Configuration for specific hooks
default_stages: [commit, push]
default_language_version:
  python: python3.11

# Exclude patterns
exclude: |
  (?x)^(
    backend/pkg/mod/.*|
    backend/gen/.*|
    \.git/.*|
    .*\.pb\.go$|
    .*\.sum$
  )$

# Fail fast: stop running hooks after first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: '2.15.0'