# SQLBoiler Configuration

[mysql]
  # Database connection parameters
  dbname = "stock_automation"
  host = "localhost"
  port = 3309
  user = "root"
  pass = "password"
  sslmode = "disable"

# Code generation parameters
output = "internal/infrastructure/dao"
pkgname = "dao"
wipe = true



