// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/drivers"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	models "github.com/boost-jp/stock-automation/internal/domain"
	cerrors "github.com/boost-jp/stock-automation/internal/errors"
	errors "github.com/boost-jp/stock-automation/internal/errors/boilerrors"
)

//go:generate go run  ../../../cmd/generator/repoinit --fields=ID,Code,Date,Rsi14,Macd,MacdSignal,MacdHistogram,Sma5,Sma25,Sma75,CreatedAt,UpdatedAt, TechnicalIndicator

// You can edit this as you like.

// TechnicalIndicator is an object representing the database table.
// Set the "validate" tags as needed.
// https://pkg.go.dev/gopkg.in/go-playground/validator.v10
type TechnicalIndicator struct {
	ID            string            `validate:""`
	Code          string            `validate:""` // 銘柄コード
	Date          time.Time         `validate:""` // 計算日
	Rsi14         types.NullDecimal `validate:""` // RSI(14日)
	Macd          types.NullDecimal `validate:""` // MACD
	MacdSignal    types.NullDecimal `validate:""` // MACDシグナル
	MacdHistogram types.NullDecimal `validate:""` // MACDヒストグラム
	Sma5          types.NullDecimal `validate:""` // 5日移動平均
	Sma25         types.NullDecimal `validate:""` // 25日移動平均
	Sma75         types.NullDecimal `validate:""` // 75日移動平均
	CreatedAt     null.Time         `validate:""` // 作成日時
	UpdatedAt     null.Time         `validate:""` // 更新日時
}

func (m *TechnicalIndicator) valid() error {
	return validate.Struct(m)
}

func NewTechnicalIndicator(
	ID string,
	Code string,
	Date time.Time,
	Rsi14 types.NullDecimal,
	Macd types.NullDecimal,
	MacdSignal types.NullDecimal,
	MacdHistogram types.NullDecimal,
	Sma5 types.NullDecimal,
	Sma25 types.NullDecimal,
	Sma75 types.NullDecimal,
	CreatedAt null.Time,
	UpdatedAt null.Time,
) (*TechnicalIndicator, error) {
	do := &TechnicalIndicator{
		ID:            ID,
		Code:          Code,
		Date:          Date,
		Rsi14:         Rsi14,
		Macd:          Macd,
		MacdSignal:    MacdSignal,
		MacdHistogram: MacdHistogram,
		Sma5:          Sma5,
		Sma25:         Sma25,
		Sma75:         Sma75,
		CreatedAt:     CreatedAt,
		UpdatedAt:     UpdatedAt,
	}
	if err := do.valid(); err != nil {
		return nil, err
	}
	return do, nil
}
