name: 🐛 バグ報告 (Bug Report)
description: バグや問題の報告を作成
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: input
    id: bug-title
    attributes:
      label: バグ概要
      placeholder: "例: 株価データ取得でAPIエラーが発生する"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      options:
        - "🔴 致命的"
        - "🟠 高"
        - "🟡 中" 
        - "🟢 低"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 問題内容
      description: 何が起こっているか・期待される動作
      placeholder: |
        ## 実際の動作
        エラーが発生してデータが取得できない

        ## 期待される動作  
        正常にデータが取得される

        ## エラーメッセージ
        ```
        Error: API request failed
        ```
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      placeholder: |
        1. アプリを起動
        2. データ収集を実行  
        3. エラーが発生
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境
      placeholder: |
        - OS: macOS
        - Go: 1.24.4
        - 環境: development