// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/drivers"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	models "github.com/boost-jp/stock-automation/internal/domain"
	cerrors "github.com/boost-jp/stock-automation/internal/errors"
	errors "github.com/boost-jp/stock-automation/internal/errors/boilerrors"
)

//go:generate go run  ../../../cmd/generator/repoinit --fields=ID,Code,Name,TargetBuyPrice,TargetSellPrice,IsActive,CreatedAt,UpdatedAt, WatchList

// You can edit this as you like.

// WatchList is an object representing the database table.
// Set the "validate" tags as needed.
// https://pkg.go.dev/gopkg.in/go-playground/validator.v10
type WatchList struct {
	ID              string
	Code            string            // 銘柄コード
	Name            string            // 銘柄名
	TargetBuyPrice  types.NullDecimal // 目標買い価格
	TargetSellPrice types.NullDecimal // 目標売り価格
	IsActive        null.Bool         // アクティブフラグ
	CreatedAt       null.Time         // 作成日時
	UpdatedAt       null.Time         // 更新日時
}

func NewWatchList(
	ID string,
	Code string,
	Name string,
	TargetBuyPrice types.NullDecimal,
	TargetSellPrice types.NullDecimal,
	IsActive null.Bool,
	CreatedAt null.Time,
	UpdatedAt null.Time,
) *WatchList {
	do := &WatchList{
		ID:              ID,
		Code:            Code,
		Name:            Name,
		TargetBuyPrice:  TargetBuyPrice,
		TargetSellPrice: TargetSellPrice,
		IsActive:        IsActive,
		CreatedAt:       CreatedAt,
		UpdatedAt:       UpdatedAt,
	}
	return do
}
