// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	cerrors "github.com/boost-jp/stock-automation/internal/errors"
	errors "github.com/boost-jp/stock-automation/internal/errors/boilerrors"
	"github.com/go-sql-driver/mysql"
)

// InsertAll inserts all rows with the specified column values, using an executor.
func (o TechnicalIndicatorSlice) InsertAll(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}
	var sql string
	vals := []interface{}{}
	for i, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())

			if queries.MustTime(row.CreatedAt).IsZero() {
				queries.SetScanner(&row.CreatedAt, currTime)
			}
			if queries.MustTime(row.UpdatedAt).IsZero() {
				queries.SetScanner(&row.UpdatedAt, currTime)
			}
		}

		if err := row.doBeforeInsertHooks(ctx, exec); err != nil {
			return err
		}

		nzDefaults := queries.NonZeroDefaultSet(technicalIndicatorColumnsWithDefault, row)
		wl, _ := columns.InsertColumnSet(
			technicalIndicatorAllColumns,
			technicalIndicatorColumnsWithDefault,
			technicalIndicatorColumnsWithoutDefault,
			nzDefaults,
		)
		if i == 0 {
			sql = "INSERT INTO `technical_indicators` " + "(`" + strings.Join(wl, "`,`") + "`)" + " VALUES "
		}
		sql += strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), len(vals)+1, len(wl))
		if i != len(o)-1 {
			sql += ","
		}
		valMapping, err := queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, wl)
		if err != nil {
			return err
		}
		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valMapping)...)
	}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, vals...)
	}

	_, err := exec.ExecContext(ctx, sql, vals...)
	if err != nil {
		var mysqlErr *mysql.MySQLError
		if errors.As(err, &mysqlErr) && mysqlErr.Number == 1062 {
			return cerrors.Wrap(cerrors.ErrAlreadyExists, "dao: unable to insert into technical_indicators")
		}
		return errors.Wrap(err, "dao: unable to insert into technical_indicators")
	}

	return nil
}

func (TechnicalIndicator) GetColumns() []string {
	return technicalIndicatorAllColumns
}

func (TechnicalIndicator) GetPKs() []string {
	return technicalIndicatorPrimaryKeyColumns
}

func (technicalIndicatorQuery) GetColumns() []string {
	return technicalIndicatorAllColumns
}

func (technicalIndicatorQuery) GetPKs() []string {
	return technicalIndicatorPrimaryKeyColumns
} // TechnicalIndicator is an object representing the database table.
type TechnicalIndicator struct {
	ID string `boil:"id" json:"id" toml:"id" yaml:"id"`
	// 銘柄コード
	Code string `boil:"code" json:"code" toml:"code" yaml:"code"`
	// 計算日
	Date time.Time `boil:"date" json:"date" toml:"date" yaml:"date"`
	// RSI(14日)
	Rsi14 types.NullDecimal `boil:"rsi_14" json:"rsi_14,omitempty" toml:"rsi_14" yaml:"rsi_14,omitempty"`
	// MACD
	Macd types.NullDecimal `boil:"macd" json:"macd,omitempty" toml:"macd" yaml:"macd,omitempty"`
	// MACDシグナル
	MacdSignal types.NullDecimal `boil:"macd_signal" json:"macd_signal,omitempty" toml:"macd_signal" yaml:"macd_signal,omitempty"`
	// MACDヒストグラム
	MacdHistogram types.NullDecimal `boil:"macd_histogram" json:"macd_histogram,omitempty" toml:"macd_histogram" yaml:"macd_histogram,omitempty"`
	// 5日移動平均
	Sma5 types.NullDecimal `boil:"sma_5" json:"sma_5,omitempty" toml:"sma_5" yaml:"sma_5,omitempty"`
	// 25日移動平均
	Sma25 types.NullDecimal `boil:"sma_25" json:"sma_25,omitempty" toml:"sma_25" yaml:"sma_25,omitempty"`
	// 75日移動平均
	Sma75 types.NullDecimal `boil:"sma_75" json:"sma_75,omitempty" toml:"sma_75" yaml:"sma_75,omitempty"`
	// 作成日時
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	// 更新日時
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *technicalIndicatorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L technicalIndicatorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TechnicalIndicatorColumns = struct {
	ID            string
	Code          string
	Date          string
	Rsi14         string
	Macd          string
	MacdSignal    string
	MacdHistogram string
	Sma5          string
	Sma25         string
	Sma75         string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	Code:          "code",
	Date:          "date",
	Rsi14:         "rsi_14",
	Macd:          "macd",
	MacdSignal:    "macd_signal",
	MacdHistogram: "macd_histogram",
	Sma5:          "sma_5",
	Sma25:         "sma_25",
	Sma75:         "sma_75",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var TechnicalIndicatorTableColumns = struct {
	ID            string
	Code          string
	Date          string
	Rsi14         string
	Macd          string
	MacdSignal    string
	MacdHistogram string
	Sma5          string
	Sma25         string
	Sma75         string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "technical_indicators.id",
	Code:          "technical_indicators.code",
	Date:          "technical_indicators.date",
	Rsi14:         "technical_indicators.rsi_14",
	Macd:          "technical_indicators.macd",
	MacdSignal:    "technical_indicators.macd_signal",
	MacdHistogram: "technical_indicators.macd_histogram",
	Sma5:          "technical_indicators.sma_5",
	Sma25:         "technical_indicators.sma_25",
	Sma75:         "technical_indicators.sma_75",
	CreatedAt:     "technical_indicators.created_at",
	UpdatedAt:     "technical_indicators.updated_at",
}

// Generated where

type whereHelpertypes_NullDecimal struct{ field string }

func (w whereHelpertypes_NullDecimal) EQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpertypes_NullDecimal) NEQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpertypes_NullDecimal) LT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_NullDecimal) LTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_NullDecimal) GT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_NullDecimal) GTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpertypes_NullDecimal) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_NullDecimal) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var TechnicalIndicatorWhere = struct {
	ID            whereHelperstring
	Code          whereHelperstring
	Date          whereHelpertime_Time
	Rsi14         whereHelpertypes_NullDecimal
	Macd          whereHelpertypes_NullDecimal
	MacdSignal    whereHelpertypes_NullDecimal
	MacdHistogram whereHelpertypes_NullDecimal
	Sma5          whereHelpertypes_NullDecimal
	Sma25         whereHelpertypes_NullDecimal
	Sma75         whereHelpertypes_NullDecimal
	CreatedAt     whereHelpernull_Time
	UpdatedAt     whereHelpernull_Time
}{
	ID:            whereHelperstring{field: "`technical_indicators`.`id`"},
	Code:          whereHelperstring{field: "`technical_indicators`.`code`"},
	Date:          whereHelpertime_Time{field: "`technical_indicators`.`date`"},
	Rsi14:         whereHelpertypes_NullDecimal{field: "`technical_indicators`.`rsi_14`"},
	Macd:          whereHelpertypes_NullDecimal{field: "`technical_indicators`.`macd`"},
	MacdSignal:    whereHelpertypes_NullDecimal{field: "`technical_indicators`.`macd_signal`"},
	MacdHistogram: whereHelpertypes_NullDecimal{field: "`technical_indicators`.`macd_histogram`"},
	Sma5:          whereHelpertypes_NullDecimal{field: "`technical_indicators`.`sma_5`"},
	Sma25:         whereHelpertypes_NullDecimal{field: "`technical_indicators`.`sma_25`"},
	Sma75:         whereHelpertypes_NullDecimal{field: "`technical_indicators`.`sma_75`"},
	CreatedAt:     whereHelpernull_Time{field: "`technical_indicators`.`created_at`"},
	UpdatedAt:     whereHelpernull_Time{field: "`technical_indicators`.`updated_at`"},
}

// TechnicalIndicatorRels is where relationship names are stored.
var TechnicalIndicatorRels = struct {
}{}

// technicalIndicatorR is where relationships are stored.
type technicalIndicatorR struct {
}

// NewStruct creates a new relationship struct
func (*technicalIndicatorR) NewStruct() *technicalIndicatorR {
	return &technicalIndicatorR{}
}

// technicalIndicatorL is where Load methods for each relationship are stored.
type technicalIndicatorL struct{}

var (
	technicalIndicatorAllColumns            = []string{"id", "code", "date", "rsi_14", "macd", "macd_signal", "macd_histogram", "sma_5", "sma_25", "sma_75", "created_at", "updated_at"}
	technicalIndicatorColumnsWithoutDefault = []string{"id", "code", "date", "rsi_14", "macd", "macd_signal", "macd_histogram", "sma_5", "sma_25", "sma_75"}
	technicalIndicatorColumnsWithDefault    = []string{"created_at", "updated_at"}
	technicalIndicatorPrimaryKeyColumns     = []string{"id"}
	technicalIndicatorGeneratedColumns      = []string{}
)

type (
	// TechnicalIndicatorSlice is an alias for a slice of pointers to TechnicalIndicator.
	// This should almost always be used instead of []TechnicalIndicator.
	TechnicalIndicatorSlice []*TechnicalIndicator
	// TechnicalIndicatorHook is the signature for custom TechnicalIndicator hook methods
	TechnicalIndicatorHook func(context.Context, boil.ContextExecutor, *TechnicalIndicator) error

	technicalIndicatorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	technicalIndicatorType                 = reflect.TypeOf(&TechnicalIndicator{})
	technicalIndicatorMapping              = queries.MakeStructMapping(technicalIndicatorType)
	technicalIndicatorPrimaryKeyMapping, _ = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, technicalIndicatorPrimaryKeyColumns)
	technicalIndicatorInsertCacheMut       sync.RWMutex
	technicalIndicatorInsertCache          = make(map[string]insertCache)
	technicalIndicatorUpdateCacheMut       sync.RWMutex
	technicalIndicatorUpdateCache          = make(map[string]updateCache)
	technicalIndicatorUpsertCacheMut       sync.RWMutex
	technicalIndicatorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var technicalIndicatorAfterSelectHooks []TechnicalIndicatorHook

var technicalIndicatorBeforeInsertHooks []TechnicalIndicatorHook
var technicalIndicatorAfterInsertHooks []TechnicalIndicatorHook

var technicalIndicatorBeforeUpdateHooks []TechnicalIndicatorHook
var technicalIndicatorAfterUpdateHooks []TechnicalIndicatorHook

var technicalIndicatorBeforeDeleteHooks []TechnicalIndicatorHook
var technicalIndicatorAfterDeleteHooks []TechnicalIndicatorHook

var technicalIndicatorBeforeUpsertHooks []TechnicalIndicatorHook
var technicalIndicatorAfterUpsertHooks []TechnicalIndicatorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TechnicalIndicator) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TechnicalIndicator) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TechnicalIndicator) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TechnicalIndicator) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TechnicalIndicator) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TechnicalIndicator) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TechnicalIndicator) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TechnicalIndicator) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TechnicalIndicator) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range technicalIndicatorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTechnicalIndicatorHook registers your hook function for all future operations.
func AddTechnicalIndicatorHook(hookPoint boil.HookPoint, technicalIndicatorHook TechnicalIndicatorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		technicalIndicatorAfterSelectHooks = append(technicalIndicatorAfterSelectHooks, technicalIndicatorHook)
	case boil.BeforeInsertHook:
		technicalIndicatorBeforeInsertHooks = append(technicalIndicatorBeforeInsertHooks, technicalIndicatorHook)
	case boil.AfterInsertHook:
		technicalIndicatorAfterInsertHooks = append(technicalIndicatorAfterInsertHooks, technicalIndicatorHook)
	case boil.BeforeUpdateHook:
		technicalIndicatorBeforeUpdateHooks = append(technicalIndicatorBeforeUpdateHooks, technicalIndicatorHook)
	case boil.AfterUpdateHook:
		technicalIndicatorAfterUpdateHooks = append(technicalIndicatorAfterUpdateHooks, technicalIndicatorHook)
	case boil.BeforeDeleteHook:
		technicalIndicatorBeforeDeleteHooks = append(technicalIndicatorBeforeDeleteHooks, technicalIndicatorHook)
	case boil.AfterDeleteHook:
		technicalIndicatorAfterDeleteHooks = append(technicalIndicatorAfterDeleteHooks, technicalIndicatorHook)
	case boil.BeforeUpsertHook:
		technicalIndicatorBeforeUpsertHooks = append(technicalIndicatorBeforeUpsertHooks, technicalIndicatorHook)
	case boil.AfterUpsertHook:
		technicalIndicatorAfterUpsertHooks = append(technicalIndicatorAfterUpsertHooks, technicalIndicatorHook)
	}
}

// One returns a single technicalIndicator record from the query.
func (q technicalIndicatorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TechnicalIndicator, error) {
	o := &TechnicalIndicator{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, cerrors.Wrap(cerrors.ErrNotFound, "dao: technical_indicators not found")
		}
		return nil, errors.Wrap(err, "dao: failed to execute a one query for technical_indicators")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TechnicalIndicator records from the query.
func (q technicalIndicatorQuery) All(ctx context.Context, exec boil.ContextExecutor) (TechnicalIndicatorSlice, error) {
	var o []*TechnicalIndicator

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dao: failed to assign all query results to TechnicalIndicator slice")
	}

	if len(technicalIndicatorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TechnicalIndicator records in the query.
func (q technicalIndicatorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to count technical_indicators rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q technicalIndicatorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dao: failed to check if technical_indicators exists")
	}

	return count > 0, nil
}

// TechnicalIndicators retrieves all the records using an executor.
func TechnicalIndicators(mods ...qm.QueryMod) technicalIndicatorQuery {
	mods = append(mods, qm.From("`technical_indicators`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`technical_indicators`.*"})
	}

	return technicalIndicatorQuery{q}
}

// FindTechnicalIndicator retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTechnicalIndicator(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*TechnicalIndicator, error) {
	technicalIndicatorObj := &TechnicalIndicator{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `technical_indicators` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, technicalIndicatorObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, cerrors.Wrap(cerrors.ErrNotFound, "dao: technical_indicators not found")
		}
		return nil, errors.Wrap(err, "dao: unable to select from technical_indicators")
	}

	if err = technicalIndicatorObj.doAfterSelectHooks(ctx, exec); err != nil {
		return technicalIndicatorObj, err
	}

	return technicalIndicatorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TechnicalIndicator) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dao: no technical_indicators provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(technicalIndicatorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	technicalIndicatorInsertCacheMut.RLock()
	cache, cached := technicalIndicatorInsertCache[key]
	technicalIndicatorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			technicalIndicatorAllColumns,
			technicalIndicatorColumnsWithDefault,
			technicalIndicatorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `technical_indicators` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `technical_indicators` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `technical_indicators` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, technicalIndicatorPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dao: unable to insert into technical_indicators")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dao: unable to populate default values for technical_indicators")
	}

CacheNoHooks:
	if !cached {
		technicalIndicatorInsertCacheMut.Lock()
		technicalIndicatorInsertCache[key] = cache
		technicalIndicatorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TechnicalIndicator.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TechnicalIndicator) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	technicalIndicatorUpdateCacheMut.RLock()
	cache, cached := technicalIndicatorUpdateCache[key]
	technicalIndicatorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			technicalIndicatorAllColumns,
			technicalIndicatorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dao: unable to update technical_indicators, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `technical_indicators` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, technicalIndicatorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, append(wl, technicalIndicatorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update technical_indicators row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by update for technical_indicators")
	}

	if !cached {
		technicalIndicatorUpdateCacheMut.Lock()
		technicalIndicatorUpdateCache[key] = cache
		technicalIndicatorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q technicalIndicatorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all for technical_indicators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected for technical_indicators")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TechnicalIndicatorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dao: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), technicalIndicatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `technical_indicators` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, technicalIndicatorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all in technicalIndicator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected all in update all technicalIndicator")
	}
	return rowsAff, nil
}

var mySQLTechnicalIndicatorUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TechnicalIndicator) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dao: no technical_indicators provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(technicalIndicatorColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTechnicalIndicatorUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	technicalIndicatorUpsertCacheMut.RLock()
	cache, cached := technicalIndicatorUpsertCache[key]
	technicalIndicatorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			technicalIndicatorAllColumns,
			technicalIndicatorColumnsWithDefault,
			technicalIndicatorColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			technicalIndicatorAllColumns,
			technicalIndicatorPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dao: unable to upsert technical_indicators, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`technical_indicators`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `technical_indicators` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dao: unable to upsert for technical_indicators")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(technicalIndicatorType, technicalIndicatorMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dao: unable to retrieve unique values for technical_indicators")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dao: unable to populate default values for technical_indicators")
	}

CacheNoHooks:
	if !cached {
		technicalIndicatorUpsertCacheMut.Lock()
		technicalIndicatorUpsertCache[key] = cache
		technicalIndicatorUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TechnicalIndicator record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TechnicalIndicator) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dao: no TechnicalIndicator provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), technicalIndicatorPrimaryKeyMapping)
	sql := "DELETE FROM `technical_indicators` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete from technical_indicators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by delete for technical_indicators")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q technicalIndicatorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dao: no technicalIndicatorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from technical_indicators")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for technical_indicators")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TechnicalIndicatorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(technicalIndicatorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), technicalIndicatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `technical_indicators` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, technicalIndicatorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from technicalIndicator slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for technical_indicators")
	}

	if len(technicalIndicatorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TechnicalIndicator) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTechnicalIndicator(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TechnicalIndicatorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TechnicalIndicatorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), technicalIndicatorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `technical_indicators`.* FROM `technical_indicators` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, technicalIndicatorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dao: unable to reload all in TechnicalIndicatorSlice")
	}

	*o = slice

	return nil
}

// TechnicalIndicatorExists checks if the TechnicalIndicator row exists.
func TechnicalIndicatorExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `technical_indicators` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dao: unable to check if technical_indicators exists")
	}

	return exists, nil
}

// Exists checks if the TechnicalIndicator row exists.
func (o *TechnicalIndicator) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TechnicalIndicatorExists(ctx, exec, o.ID)
}
