// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/types"
)

//go:generate go run  ../../../cmd/generator/repoinit --fields=ID,Code,Name,Shares,PurchasePrice,PurchaseDate,CreatedAt,UpdatedAt, Portfolio

// You can edit this as you like.

// Portfolio is an object representing the database table.
// Set the "validate" tags as needed.
// https://pkg.go.dev/gopkg.in/go-playground/validator.v10
type Portfolio struct {
	ID            string
	Code          string        // 銘柄コード
	Name          string        // 銘柄名
	Shares        int           // 保有株数
	PurchasePrice types.Decimal // 購入価格
	PurchaseDate  time.Time     // 購入日
	CreatedAt     null.Time     // 作成日時
	UpdatedAt     null.Time     // 更新日時
}

func NewPortfolio(
	ID string,
	Code string,
	Name string,
	Shares int,
	PurchasePrice types.Decimal,
	PurchaseDate time.Time,
	CreatedAt null.Time,
	UpdatedAt null.Time,
) *Portfolio {
	do := &Portfolio{
		ID:            ID,
		Code:          Code,
		Name:          Name,
		Shares:        Shares,
		PurchasePrice: PurchasePrice,
		PurchaseDate:  PurchaseDate,
		CreatedAt:     CreatedAt,
		UpdatedAt:     UpdatedAt,
	}
	return do
}
