// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/types"
)

//go:generate go run  ../../../cmd/generator/repoinit --fields=ID,Code,Date,OpenPrice,HighPrice,LowPrice,ClosePrice,Volume,CreatedAt,UpdatedAt, StockPrice

// You can edit this as you like.

// StockPrice is an object representing the database table.
// Set the "validate" tags as needed.
// https://pkg.go.dev/gopkg.in/go-playground/validator.v10
type StockPrice struct {
	ID         string
	Code       string        // 銘柄コード
	Date       time.Time     // 取引日
	OpenPrice  types.Decimal // 始値
	HighPrice  types.Decimal // 高値
	LowPrice   types.Decimal // 安値
	ClosePrice types.Decimal // 終値
	Volume     int64         // 出来高
	CreatedAt  null.Time     // 作成日時
	UpdatedAt  null.Time     // 更新日時
}

func NewStockPrice(
	ID string,
	Code string,
	Date time.Time,
	OpenPrice types.Decimal,
	HighPrice types.Decimal,
	LowPrice types.Decimal,
	ClosePrice types.Decimal,
	Volume int64,
	CreatedAt null.Time,
	UpdatedAt null.Time,
) *StockPrice {
	do := &StockPrice{
		ID:         ID,
		Code:       Code,
		Date:       Date,
		OpenPrice:  OpenPrice,
		HighPrice:  HighPrice,
		LowPrice:   LowPrice,
		ClosePrice: ClosePrice,
		Volume:     Volume,
		CreatedAt:  CreatedAt,
		UpdatedAt:  UpdatedAt,
	}
	return do
}
