version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: stock-automation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock_automation
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stockpass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
    driver: local