database:
  host: localhost
  port: 3306
  user: root
  password: password
  database: stock_automation

api:
  yahoo_finance:
    base_url: https://query1.finance.yahoo.com
    timeout: 30s
    retry_count: 3
    retry_wait: 1s

scheduler:
  price_update_interval: 5m
  settings_update_interval: 30m
  cleanup_time: "02:00"
  
notification:
  slack:
    webhook_url: ${SLACK_WEBHOOK_URL}
    
market:
  open_hour: 9
  close_hour: 15
  
data:
  cleanup_days: 365
  batch_size: 100
  
logging:
  level: info
  format: json